//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goof_.Models
{
    using System;
    using System.Collections.Generic;

	public partial class Mascotas
	{
		public int IdMascota { get; set; }
		public string Nombre { get; set; }
		public string Genero { get; set; }
		public string Raza { get; set; }
		public int Edad { get; set; }
		public string ColorPelo { get; set; }
		public string Peso { get; set; }
		public int Vacunas { get; set; }
		public int Papeles { get; set; }
		public Nullable<int> LikeCount { get; set; }
		public int IdUsuario { get; set; }

		public virtual Usuarios Usuarios { get; set; }

	}
}
